language: generic

env:
  jobs:
    - OS_TYPE=fedora OS_VERSION=31
    - OS_TYPE=amazonlinux OS_VERSION=2
    - OS_TYPE=centos OS_VERSION=8    
    - OS_TYPE=centos OS_VERSION=7
    - OS_TYPE=centos OS_VERSION=6

services:
  - docker

install:
  - ./crypt-keeper generate ${OS_TYPE} ${OS_VERSION}

script:
  - ./crypt-keeper build ${OS_TYPE} ${OS_VERSION}

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./crypt-keeper push ${OS_TYPE} ${OS_VERSION}

