#!/usr/bin/env bash

DOCKER_REGISRY_USER=getpagespeed

function generate() {
    SOURCES=${SOURCES-/sources}
    OUTPUT=${OUTPUT-/output}
    WORKSPACE=${WORKSPACE-/workspace}
    RPM_BUILD_DIR=${RPM_BUILD_DIR-/rpmbuild}

    DISTRO=${1-fedora}
    RELEASE=${2-latest}
    # Last EPEL is 7 so far:
    RELEASE_EPEL=${2-7}

    ROOT=$(pwd)/${DISTRO}/${RELEASE}/
    ASSETS=${ROOT}/assets
    DOCKERFILE=${ROOT}/Dockerfile
    rm -rf ${ROOT} && mkdir -p ${ROOT}

    # prepare files
    cp -R ./assets ${ROOT}/.
    # cp LICENCE README.md
    YUM="yum"
    PACKAGES="rpm-build rpmdevtools yum-utils rpmlint"
    case "${DISTRO}" in
        centos|cloudrouter*centos)
            EXTRA_RELEASES="epel-release centos-release-scl https://extras.getpagespeed.com/release-el${RELEASE_EPEL}-latest.rpm";
            PACKAGES="${PACKAGES} @buildsys-build"
            # @buildsys-build is to better "emulate" mock by preinstalling gcc thus preventing devtoolset-* lookup for "BuildRequires: gcc"
            if [ "$RELEASE" == "6" ]; then
                # Should be in the .spec as well. Our build env isn't "clean OS" but we want faster builds!
                PACKAGES="${PACKAGES} devtoolset-7-gcc-c++ devtoolset-7-binutils"
            fi
            ;;
        fedora)
            YUM="dnf";
            PACKAGES="'dnf-command(builddep)'";
            ;;
    esac
    # header
    cat > ${DOCKERFILE} << EOF
FROM ${DISTRO}:${RELEASE}
MAINTAINER "Arun Neelicattu" <arun.neelicattu@gmail.com>

ENV WORKSPACE=${WORKSPACE} \\
    SOURCES=${SOURCES} \\
    OUTPUT=${OUTPUT} \\
    RPM_BUILD_DIR=${RPM_BUILD_DIR}

RUN useradd builder -G wheel
RUN rm -rf /etc/yum.repos.d/{CentOS-Sources.repo,CentOS-Sources.repo} $(test "$EXTRA_RELEASES" && echo "&& yum -y install ${EXTRA_RELEASES}")
RUN [ -f "/etc/yum.repos.d/CentOS-SCLo-scl-rh.repo" ] && sed -i '/centos-sclo-rh-source/,//d' /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo
RUN [ -f "/etc/yum.repos.d/CentOS-SCLo-scl.repo" ] && sed -i '/centos-sclo-sclo-source/,//d' /etc/yum.repos.d/CentOS-SCLo-scl.repo
RUN ${YUM} -y install ${PACKAGES} \\
    && ${YUM} -y clean all \\
    && ln -sf \${RPM_BUILD_DIR} /root/rpmbuild \\
    && mkdir -p \${SOURCES} \\
        \${OUTPUT} 
RUN runuser builder rpmdev-setuptree
VOLUME ["\${SOURCES}", "\${OUTPUT}"]

ADD ./assets/build /usr/bin/build
ADD ./assets/rpmlint.config /etc/rpmlint/custom.config

CMD ["build"]
EOF
}

function map-all() {
    while IFS=' ' read -r -a input; do 
        $1 ${input[0]} ${input[1]}
    done < ./defaults
}

function docker-image-name() {
    DISTRO=${1}
    VERSION=${2}
    echo -n "${DOCKER_REGISRY_USER}/rpmbuilder:${DISTRO/\//-}-${VERSION}"
   
}

function build() {
    DISTRO=${1}
    VERSION=${2}
    cd ${DISTRO}/${VERSION} \
        && docker build -t $(docker-image-name ${DISTRO} ${VERSION}) .
    cd -
}

function push() {
    DISTRO=${1}
    VERSION=${2}
    docker push $(docker-image-name ${DISTRO} ${VERSION})
}

case "$1" in
    generate|build|push)
        if [ "$2" == "all" ]; then
            map-all $1
        else
            $1 $2 $3 
        fi ;;
esac
