#!/usr/bin/env bash

# use exit codes of failing commands
set -exo pipefail

SOURCES=${SOURCES-/sources}
OUTPUT=${OUTPUT-${SOURCES}}

# Use custom rpmlint config per repository, if such exists
[ -f ${SOURCES}/rpmlint.config ] && mv -f ${SOURCES}/rpmlint.config /etc/rpmlint/custom.config
# Run optional per-repo file with extra build preparations needed like setting up more repos
[ -f ${SOURCES}/prepare.sh ] && bash ${SOURCES}/prepare.sh

# each repo can go with rpmmacros (useful for building multiple branches while retaining same spec)
[ -f ${SOURCES}/rpmmacros ] \
  && cat ${SOURCES}/rpmmacros >> /root/.rpmmacros \
  && chown root:root /root/.rpmmacros 

# Use rpm instead of rpmbuild to avoid bad exit in EL6
RPM_BUILD_SOURCES=$(rpm --eval '%{_sourcedir}')
RPM_BUILD_RPMS=$(rpm --eval '%{_rpmdir}')
RPM_BUILD_SRPMS=$(rpm --eval '%{_srcrpmdir}')
RPM_BUILD_SPECS=$(rpm --eval '%{_specdir}')

echo $ RPM_BUILD_SPECS
# copy any .spec filess to rpmbuild/SPECS directory
find ${SOURCES} -mindepth 1 -maxdepth 1 -name "*.spec" \
    -exec cp -R {} ${RPM_BUILD_SPECS}/. \;

# copy any non-spec files/dirs to rpmbuild/SOURCES directory
find ${SOURCES} -mindepth 1 -maxdepth 1 ! -name "*.spec" \
    -exec cp -R {} ${RPM_BUILD_SOURCES}/. \;
    
# fix permissions on working copy
chown root:root /root/rpmbuild    

# VMOD tests during build:
# varnishd is dropping to user nobody/varnish, and as such doesn't have access in /root/
chmod 0755 /root

# With SCLO repos in place, yum-builddep might resolve "BuildRequires: gcc" to devtoolset-4-gcc
# In Docker image we pre-install build sys root (gcc) to mimic mock better and avoid this bad lookup
BUILDDEP_CMD="yum-builddep"
command -v dnf > /dev/null 2>&1 && BUILDDEP_CMD="dnf builddep"

# enable specified repositories before build
if [[ -n ${ENABLE_REPOS} ]]; then
  yum-config-manager --enable "${ENABLE_REPOS}"
fi

for specFile in ${RPM_BUILD_SPECS}/*.spec; do

  if [[ -n ${RPMLINT} && "${RPMLINT}" != 0 ]]; then
    # check the spec file for obvious errors using rpmlint
    rpmlint $specFile
  fi

  # install build requires
  ${BUILDDEP_CMD} -y $specFile
  spectool --sourcedir --get-files $specFile

  # build SRPM, also allows to fail quicker
  rpmbuild -bs $specFile

  if [[ -n ${RPMLINT} ]]; then
    # SRPM built successfully. Check it using rpmlint
    rpmlint ${RPM_BUILD_SRPMS}/*.rpm
  fi

  mv ${RPM_BUILD_SRPMS}/*.rpm ${OUTPUT}

  if [[ -z ${SRPM_ONLY} ]]; then
    # attempting to build RPM now
    rpmbuild -ba $specFile

    if [[ -n ${RPMLINT} && "${RPMLINT}" != 0 ]]; then
      # RPM built successfully. Check it using rpmlint
      rpmlint ${RPM_BUILD_RPMS}/*/*.rpm
    fi

    mv ${RPM_BUILD_RPMS}/*/*.rpm ${OUTPUT}
  fi
done

# fix uids
if [ -z "${OUTPUT_UID}" ]; then
   chown -R ${OUTPUT_UID}:${OUTPUT_UID} ${OUTPUT}/*
fi
