name: CI
on: [push]
jobs:
  one:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [centos]
        version: [6, 7, 8]
        include:
          - os: fedora
            version: 34
          - os: fedora
            version: 35
          - os: amazonlinux
            version: 2
          - os: opensuse
            version: 15
    steps:
      - uses: actions/checkout@v2
      - name: "Set up RPM client User-Agent for images"
        run: |
          sed -i 's@XXXXXXXXXX@rpmbuilder@g' assets/transient/fix-getpagespeed-repo.sh
          sed -i 's@XXXXXXXXXX@rpmbuilder@g' assets/transient/user-agent.py
      - name: Generate Dockerfile
        run: ./crypt-keeper.sh generate ${{ matrix.os }} ${{ matrix.version }}
      - name: Build Docker image
        run: ./crypt-keeper.sh build ${{ matrix.os }} ${{ matrix.version }}
      - name: Log in to Docker Hub
        run: docker login -u="${{ secrets.DOCKER_USER }}" -p="${{ secrets.DOCKER_PASS }}"
      - name: Push to Docker Hub
        run: ./crypt-keeper.sh push ${{ matrix.os }} ${{ matrix.version }}
