name: CI
on:
  push:
  schedule:
    - cron: "35 */6 * * *"
jobs:
  one:
    runs-on: ubuntu-latest
    strategy:
      # allow pushing successfully built images anyway
      fail-fast: false
      matrix:
        os: [centos]
        version: [6, 7, 8, 9]
        include:
          - os: fedora
            version: 34
          - os: fedora
            version: 35
          - os: fedora
            version: 36
          - os: fedora
            version: 37
          - os: fedora
            version: 38
          - os: fedora
            version: 39
          - os: amazonlinux
            version: 2
          - os: amazonlinux
            version: 2023
          - os: opensuse
            version: 15
    steps:
      - uses: actions/checkout@v2
      - name: "Set up RPM client User-Agent for images"
        run: |
          sed -i "s@XXXXXXXXXX@${{ secrets.RPMBUILDER_UA }}@g" assets/transient/fix-getpagespeed-repo.sh
          sed -i "s@XXXXXXXXXX@${{ secrets.RPMBUILDER_UA }}@g" assets/transient/user-agent.py
      - name: Generate Dockerfile
        run: ./crypt-keeper.sh generate ${{ matrix.os }} ${{ matrix.version }}
      - name: Build Docker image
        run: ./crypt-keeper.sh build ${{ matrix.os }} ${{ matrix.version }}

      - name: Test RPM Build
        run: |
          ls -al centos
          docker run --rm -v $PWD/sample.spec:/sample.spec:ro YOUR_DOCKER_IMAGE_NAME rpmbuild -ba /sample.spec
          # Replace YOUR_DOCKER_IMAGE_NAME with the name/tag of your Docker image
          # Assumes sample.spec is in the repository root        

      - name: Log in to Docker Hub
        run: docker login -u="${{ secrets.DOCKER_USER }}" -p="${{ secrets.DOCKER_PASS }}"
      - name: Push to Docker Hub
        run: ./crypt-keeper.sh push ${{ matrix.os }} ${{ matrix.version }}
