name: CI
on: [push]
jobs:
  one:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [centos]
        version: [6, 7, 8]
        include:
          - os: fedora
            version: 33
          - os: amazonlinux
            version: 2
    steps:
      - uses: actions/checkout@v2
      - name: Generate Dockerfile
        run: ./crypt-keeper generate ${{ matrix.os }} ${{ matrix.version }}
      - name: Build Docker image
        run: ./crypt-keeper build ${{ matrix.os }} ${{ matrix.version }}
      - name: Log in to Docker Hub
        run: docker login -u="${{ secrets.DOCKER_USER }}" -p="${{ secrets.DOCKER_PASS }}"
      - name: Push to Docker Hub
        run: ./crypt-keeper push ${{ matrix.os }} ${{ matrix.version }}